### ISSUE TITLE
Getting Error in your code

### ISSUE THREAD

**Issue by tejasklodha** [Marchuck/OPC_DA_Proxy#1]
Dear Sir,

Can I Fetch data from OPC DA Server?
I want to fetch data from OPC DA Server.
Can it possible by OPC_DA_Proxy?

I am getting error on code:
 server.Connect(url, new Opc.ConnectData(new System.Net.NetworkCredential()));

Exception is :  

```
An exception of type 'Opc.ConnectFailedException' occurred in OpcNetApi.dll but was not handled in user code
Additional information: E_NETWORK_ERROR
Could not connect to server.
Intellution.OPCiFIX.1
```

Ned your help to resolve this error.

Thanks,

**Comment by Marchuck** [comment]
Make sure your server is running: I assume you are using Windows, so you can download  [Matrikon OPC Explorer](https://www.matrikonopc.com/products/opc-desktop-tools/opc-explorer.aspx), and check connection with this software.

additionally, to make it work, you may also need to run Visual Studio (or other IDE you are using to execute program) as Administrator.

Then you could have access on localhost 

If you want to have access to your server from other computers, you can [setup proxy for this purpose](https://github.com/icflorescu/iisexpress-proxy)

**Comment by tejasklodha** [comment]
Dear Sir,

I already install  Matrikon OPC Explorer and able to view my simulator and open Visual studio as administrator.

![screenshot_2](https://cloud.githubusercontent.com/assets/25738779/26240379/7794ca4c-3c9e-11e7-95a5-301308edbdaf.png)

And I only change below code 

Before 

`connector = new OpcDaConnector("opcda://localhost/" + SERVER_NAME, browsableGroups);`

after 

` connector = new OpcDaConnector("opcda://localhost/" + "Graybox.Simulator.1", browsableGroups);`

But still page not load and show below information on web page
![screenshot_1](https://cloud.githubusercontent.com/assets/25738779/26240475/c8d9b35e-3c9e-11e7-8883-da3c455fc7fb.png)


Need your help?

Thanks,

**Comment by Marchuck** [comment]
I didn't put there anything, let test the REST API if it is working after launch.

open web browser and check  [REST API call](https://github.com/Marchuck/OPC_DA_Proxy/blob/master/OPC_DA_Proxy/Controllers/OpcDaController.cs)

GET localhost:port/api/OpcDa

However, I will update it tomorrow, to enable more features (browse all nodes, maybe some UI at the startup)

hope it helped

Have a nice day

**Comment by tejasklodha** [comment]
Dear Sir,

Thanks for reply.
I Getting only below line on web page when I browse "http://localhost:53617/api/OpcDa"

`<ArrayOfItemValueResult xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Opc.Da" i:nil="true"/>`

No variable populate here.
What can I do when I want any variable value here?

Thanks,

**Comment by Marchuck** [comment]
visit https://github.com/Marchuck/OPC_DA_Proxy/blob/master/OPC_DA_Proxy/OpcDaClient/OpcDaRunner.cs

in your code change signals you want to subscribe, see AiSignals() in OpcDaRunner and change it for your needs.

Basically, opcDaClient creates subscription at app startup, with server variable, so REST API holds more recent value of changes to subscribed data.

**Comment by tejasklodha** [comment]
Dear Sir,

## Awesome.....
Now I am able to get data from my OPC DA simulator as below.

```
<ArrayOfItemValueResult xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/Opc.Da">
<ItemValueResult>
<m_clientHandle xmlns="http://schemas.datacontract.org/2004/07/Opc" i:nil="true"/>
<m_itemName xmlns="http://schemas.datacontract.org/2004/07/Opc">numeric.sin.float</m_itemName>
<m_itemPath xmlns="http://schemas.datacontract.org/2004/07/Opc" i:nil="true"/>
<m_serverHandle xmlns:d3p1="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.datacontract.org/2004/07/Opc" i:type="d3p1:int">1</m_serverHandle>
<m_quality>
<m_limitBits>none</m_limitBits>
<m_qualityBits>good</m_qualityBits>
<m_vendorBits>0</m_vendorBits>
</m_quality>
<m_qualitySpecified>true</m_qualitySpecified>
<m_timestamp>2017-05-19T15:11:44.5481945+05:30</m_timestamp>
<m_timestampSpecified>true</m_timestampSpecified>
<m_value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:float">-97.4597244</m_value>
<m_diagnosticInfo i:nil="true"/>
<m_resultID xmlns:d3p1="http://schemas.datacontract.org/2004/07/Opc">
<NA xmlns:d4p1="http://www.w3.org/2001/XMLSchema" xmlns="" i:type="d4p1:string">S_OK</NA>
<NS xmlns:d4p1="http://www.w3.org/2001/XMLSchema" xmlns="" i:type="d4p1:string">http://opcfoundation.org/DataAccess/</NS>
<CO xmlns:d4p1="http://www.w3.org/2001/XMLSchema" xmlns="" i:type="d4p1:int">0</CO>
</m_resultID>
</ItemValueResult>
<ItemValueResult>
<m_clientHandle xmlns="http://schemas.datacontract.org/2004/07/Opc" i:nil="true"/>
<m_itemName xmlns="http://schemas.datacontract.org/2004/07/Opc">textual.color</m_itemName>
<m_itemPath xmlns="http://schemas.datacontract.org/2004/07/Opc" i:nil="true"/>
<m_serverHandle xmlns:d3p1="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.datacontract.org/2004/07/Opc" i:type="d3p1:int">2</m_serverHandle>
<m_quality>
<m_limitBits>none</m_limitBits>
<m_qualityBits>good</m_qualityBits>
<m_vendorBits>0</m_vendorBits>
</m_quality>
<m_qualitySpecified>true</m_qualitySpecified>
<m_timestamp>2017-05-19T15:11:44.5481945+05:30</m_timestamp>
<m_timestampSpecified>true</m_timestampSpecified>
<m_value xmlns:d3p1="http://www.w3.org/2001/XMLSchema" i:type="d3p1:string">Green</m_value>
<m_diagnosticInfo i:nil="true"/>
<m_resultID xmlns:d3p1="http://schemas.datacontract.org/2004/07/Opc">
<NA xmlns:d4p1="http://www.w3.org/2001/XMLSchema" xmlns="" i:type="d4p1:string">S_OK</NA>
<NS xmlns:d4p1="http://www.w3.org/2001/XMLSchema" xmlns="" i:type="d4p1:string">http://opcfoundation.org/DataAccess/</NS>
<CO xmlns:d4p1="http://www.w3.org/2001/XMLSchema" xmlns="" i:type="d4p1:int">0</CO>
</m_resultID>
</ItemValueResult>
</ArrayOfItemValueResult>

```

## Thanks you so much your quick help


Thanks,
Tejas Lodha

**Comment by Marchuck** [comment]
I am happy you resolved problem. Do not hestitate to leave a star :)

**Comment by tejasklodha** [comment]
Dear Sir,

Already did... : )
I am happy to do this...


Thanks
