### ISSUE TITLE
How can Host this site to cloud?

### ISSUE THREAD

**Issue by tejasklodha** [Marchuck/OPC_DA_Proxy#2]
Dear Sir,

I am able to show my PLC parameter on web by using your code.
But How can I deploy this web app to cloud...?

Because my PLC is in local network so even I deploy to cloud but from cloud how can I access my PLC by using "opcda://192.168.0.5/Graybox.Simulator.1"

because link "opcda://192.168.0.5/Graybox.Simulator.1" only accessible in local network..
Are you think any solution ?

Thanks,

**Comment by Marchuck** [comment]
for other clients use this
https://github.com/icflorescu/iisexpress-proxy 
setup proxy to map 53617 to your desired port(3000 for example) <- this is due to windows firewall protection

then check IP of computer you run c# app (proxy)

then access to your server data is via opc_da_proxy - c# app:
"http://HOST_ADDRESS:PORT/api/OpcDa"

in case of problems you may need add rule to unlock ports on windows

**Comment by Marchuck** [comment]
this allows non-localhost users to access data from PLC via c# app

**Comment by tejasklodha** [comment]
Dear Sir,

Is it work for cloud also?
Means I host this web app on Azure cloud or Godaddy on internet then still web application work fine?

Thanks,

**Comment by Marchuck** [comment]
Only when your OPC server and opc_da_proxy is running. 
I am not sure about cloud - I used this service to connect to fetch OPC workspace from Android Client App.

**Comment by tejasklodha** [comment]
Ok....
thanks for your help...
I have one another query that how can I read read Node value ?

```
connector.selectGroup("AI").readNode("FIX.WYSOKOSC.F_CV").execute
connector.selectGroup("AI").writeValue(33).intoNode("FIX.WYSOKOSC.F_CV").execute();
```

Means I can saw below code but not working and give error that 

`OpcDaConnector' does not contain a definition for 'selectGroup' and no extension method 'selectGroup' accepting a first argument of type 'OpcDaConnector' could be found`

Its more helpful for me.

Thanks,

**Comment by Marchuck** [comment]
sorry, this is the template code, I didn't yet implemented this. The purpose of this project is to interact with opc server via opc_da_proxy, I mean: REST API, not the code itself.

**Comment by Marchuck** [comment]
I will update the code tomorrow with cleaner syntax and more features, but today I have no time for this.

**Comment by tejasklodha** [comment]
Dear Sir

Ok,
Update this post when you implement it.

Thanks for your support.

**Comment by Marchuck** [comment]
Hello @tejasklodha 

I already updated this repository, I cleaned code as much as possible. Now subscribing to nodes is automated, no node hardcoding is needed.

You can also browse nodes content now, 
I plan to implement writing/reading nodes via REST API and improve UI (for now I've added first json response from OPC server)

hope it help you

cheers

Łukasz

**Comment by tejasklodha** [comment]
Dear Sir,


In new code I just change below line.
 public static String SERVER_NAME = "Graybox.Simulator.1";

After changes , Run this new project and get error in code and also check previous code which is working fine....

Error on below line in OpcDaConnector class

   BrowseElement[] dirContent = repository[dir.ItemName];


Error is as below.

```
An exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in mscorlib.dll but was not handled in user code
Additional information: The given key was not present in the dictionary.
```


Thanks,
