### ISSUE TITLE
Error in connection

### ISSUE THREAD

**Issue by tejasklodha** [Marchuck/OPC_DA_Proxy#6]
I am getting below error on below line while connect with my plc..

` server.Connect(url, new Opc.ConnectData(new System.Net.NetworkCredential()));`

```
An exception of type 'System.InvalidCastException' occurred in OpcNetApi.dll but was not handled in user code
Additional information: Unable to cast COM object of type 'System.__ComObject' to interface type 'OpcRcw.Comn.IOPCServerList2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{9DD0B56C-AD9E-43EE-8305-487F3188BF7A}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
```

Need your help

**Comment by tejasklodha** [comment]
Dear Sir,

I am able to fetch data by using Matrikon OPC Explorer

any update?

Thanks,

**Comment by Marchuck** [comment]
Hello Tejas,
Make sure you run your IDE as Administrator.

I pushed changes to master already, 
I have automated browsing nodes of workspace, (I am using Proficy HMI iFIX SCADA simulator for OPC server).

In addition, I made possibility to write / read single nodes via REST API. Pub/Sub pattern also should work decently.

If you need more advanced help, we can discuss the problem via email (lukmar993@gmail.com)

Cheers!

**Comment by tejasklodha** [comment]
Dear Sir,

facing same issue even open in Administrator

```
An exception of type 'System.InvalidCastException' occurred in OpcNetApi.dll but was not handled in user code

Additional information: Unable to cast COM object of type 'System.__ComObject' to interface type 'OpcRcw.Comn.IOPCServerList2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{9DD0B56C-AD9E-43EE-8305-487F3188BF7A}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
```
I changed code as below in OpcDaRunner class..
`            connector = new OpcDaConnector("opcda://192.168.111.221/BR.OPC.Server_AR");`


I am able to browse OPC value as below..
![screenshot_1](https://cloud.githubusercontent.com/assets/25738779/26788942/6709a5e4-4a2c-11e7-8e8c-4197785c01af.png)



Thanks,
